### ISSUE TITLE
Выявленные недостатки и потенциальные проблемы с производительностью

### ISSUE THREAD

**Issue by yangjiuyue18** [sevryukov/UDF-optimization#1]
Вложенные функции
Функция F_WORKS_LIST зависит от двух вложенных функций F_WORKITEMS_COUNT_BY_ID_WORK и F_EMPLOYEE_FULLNAME. Поскольку для каждой строки результирующего набора необходимо выполнить отдельный вызов каждой из этих функций, это может привести к проблемам с производительностью.
Использование переменной таблицы
Функция F_WORKS_LIST использует переменную таблицы @RESULT для хранения результатов запроса. Переменные таблицы являются временными структурами, которые хранятся в памяти, и вставка данных в них может быть медленнее, чем прямая вставка в таблицу.
Строковые операции в скалярной функции
Функция F_EMPLOYEE_FULLNAME формирует полное имя сотрудника, объединяя строки и манипулируя символами. Это неэффективно по сравнению с использованием функций базы данных, предназначенных для таких задач.
COALESCE с F_EMPLOYEE_GET
Функция F_EMPLOYEE_FULLNAME использует COALESCE вместе с вызовом другой функции F_EMPLOYEE_GET. Это добавляет еще один уровень сложности и потенциальные накладные расходы на производительность.
Отсутствие индексов
В следующих таблицах отсутствуют соответствующие индексы для определенных столбцов:
В таблице Works:
Отсутствие индекса по столбцам: Id_Work, StatusId.
Проблема: в ORDER BY используется Id_Work, а также StatusId используется для JOIN. Отсутствие индекса может привести к снижению производительности запросов.
В таблице WorkItem:
Отсутствие индекса по столбцам: id_work, id_analiz, is_complit.
Проблема: в F_WORKITEMS_COUNT_BY_ID_WORK используется id_work, а также id_analiz и is_complit в качестве условий фильтрации.
В таблице Employee:
Отсутствие индекса по столбцу: Id_Employee.
Проблема: в F_EMPLOYEE_FULLNAME используется Id_Employee в качестве условия фильтрации. Отсутствие индекса может привести к снижению производительности запросов.
Широкие столбцы
В следующих таблицах имеются широкие символьные столбцы:
В таблице Works:
Широкие столбцы: FIO, DoctorFIO, Material_Comment, DoctorEmail, OrganizationFax, OrganizationEmail.
Проблема: все эти столбцы имеют тип VARCHAR или NVARCHAR с большим размером, что может негативно повлиять на производительность запросов.
В таблице Employee:
Широкие столбцы: Login_Name, Name, Patronymic, Surname, Email.
Проблема: все эти столбцы имеют тип VARCHAR или NVARCHAR с большим размером, что может негативно повлиять на производительность запросов.
st113021 Ян Тяньюй

**Comment by sevryukov** [comment]
@yangjiuyue18 в issue нужно задавать вопросы по заданию, а решения нужно предоставлять в виде pull request. Прочитайте внимательно описание задания.
